### ISSUE TITLE
Do I need all of these steps?

### ISSUE THREAD

**Issue by vaulttech** [WZBSocialScienceCenter/germalemma#1]
Hi,

I am not sure if I understood the code right, but I am guessing that this library uses pattern to find the lemmas in the TIGER corpus and then generates a file `lemmata.pickle` that can be loaded and used directly.

My question is: is it possible for me to just have the lemmata.pickle and not have to do all these steps? This would make life much easier (I just need a simple lemmatizer, and this looked perfect).

**Comment by internaut** [comment]
Hi,
yes you need these steps and actually it's not that hard to download the TIGER corpus file, is it? The reason I didn't include the corpus file is because of license issues.

You didn't understand the code right. It doesn't generate a lemmata from the TIGER corpus with pattern -- this wouldn't make any sense because the lemmata are already *in* the TIGER corpus. It uses this corpus as lemmata dictionary lookup (with some improvements like noun and adjective decomposition). It uses pattern only as a fallback when a word is not in the lemmata dictionary.

And of course you will need to POS tag your tokens before -- otherwise the results would be very inaccurate.
